package com.softly.fonoteca.Vistas;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class AlbumVista extends JFrame implements CRUDView {
    public JTextField txtIdAlbum;
    public JTextField txtTitulo;
    public JTextField txtSello;
    public JTextField txtFecha;
    public JComboBox cmbGenero;
    public JLabel selloDiscograficoLabel;
    public JLabel tituloAlbumLabel;
    public JLabel IDAlbumLabel;
    public JLabel fechaLanzamientoLabel;
    public JLabel generoPrincipalLabel;
    public JPanel contentPane;
    public JLabel albumnesLabel;
    public JButton agregarButton;
    public JButton modificarButton;
    public JButton eliminarButton;
    public JButton limpiarCamposButton;
    public JButton regresarButton;
    public JTable tablaAlbumnes;
    public JTextField txtSearch;

    public AlbumVista() {
        super.setContentPane(contentPane);
    }


    @Override
    public JButton getBtnAgregar() {
        return agregarButton;
    }

    @Override
    public JButton getBtnModificar() {
        return modificarButton;
    }

    @Override
    public JButton getBtnEliminar() {
        return eliminarButton;
    }

    @Override
    public JButton getBtnRegresarMenu() {
        return regresarButton;
    }

    @Override
    public JButton getBtnLimpiar() {
        return limpiarCamposButton;
    }

    @Override
    public String getSearchText() {
        return txtSearch.getText();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(8, 3, new Insets(10, 50, 50, 50), -1, -1));
        contentPane.setBackground(new Color(-1705241));
        IDAlbumLabel = new JLabel();
        IDAlbumLabel.setText("ID Album: ");
        contentPane.add(IDAlbumLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tituloAlbumLabel = new JLabel();
        tituloAlbumLabel.setText("Titulo album: ");
        contentPane.add(tituloAlbumLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtIdAlbum = new JTextField();
        txtIdAlbum.setEditable(false);
        txtIdAlbum.setEnabled(false);
        contentPane.add(txtIdAlbum, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, -1), new Dimension(150, 25), new Dimension(250, -1), 0, false));
        txtTitulo = new JTextField();
        txtTitulo.setText("");
        contentPane.add(txtTitulo, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, -1), new Dimension(150, 25), new Dimension(250, -1), 0, false));
        selloDiscograficoLabel = new JLabel();
        selloDiscograficoLabel.setText("Sello Discografico: ");
        contentPane.add(selloDiscograficoLabel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtSello = new JTextField();
        contentPane.add(txtSello, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, -1), new Dimension(150, 25), new Dimension(250, -1), 0, false));
        fechaLanzamientoLabel = new JLabel();
        fechaLanzamientoLabel.setText("Fecha Lanzamiento: ");
        contentPane.add(fechaLanzamientoLabel, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtFecha = new JTextField();
        contentPane.add(txtFecha, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, -1), new Dimension(150, 25), new Dimension(250, -1), 0, false));
        generoPrincipalLabel = new JLabel();
        generoPrincipalLabel.setText("Genero Principal");
        contentPane.add(generoPrincipalLabel, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cmbGenero = new JComboBox();
        contentPane.add(cmbGenero, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, -1), null, new Dimension(250, -1), 0, false));
        albumnesLabel = new JLabel();
        Font albumnesLabelFont = this.$$$getFont$$$(null, -1, 28, albumnesLabel.getFont());
        if (albumnesLabelFont != null) albumnesLabel.setFont(albumnesLabelFont);
        albumnesLabel.setIcon(new ImageIcon(getClass().getResource("/images/128/album.png")));
        albumnesLabel.setText("Albumnes");
        contentPane.add(albumnesLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        agregarButton = new JButton();
        agregarButton.setBackground(new Color(-331277));
        agregarButton.setIcon(new ImageIcon(getClass().getResource("/images/24/save.png")));
        agregarButton.setText("Agregar");
        contentPane.add(agregarButton, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, -1), null, new Dimension(250, -1), 0, false));
        modificarButton = new JButton();
        modificarButton.setBackground(new Color(-331277));
        modificarButton.setIcon(new ImageIcon(getClass().getResource("/images/24/edit.png")));
        modificarButton.setText("Modificar");
        contentPane.add(modificarButton, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, -1), null, new Dimension(250, -1), 0, false));
        eliminarButton = new JButton();
        eliminarButton.setBackground(new Color(-331277));
        eliminarButton.setIcon(new ImageIcon(getClass().getResource("/images/24/delete.png")));
        eliminarButton.setText("Eliminar");
        contentPane.add(eliminarButton, new GridConstraints(6, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, -1), null, new Dimension(250, -1), 0, false));
        limpiarCamposButton = new JButton();
        limpiarCamposButton.setBackground(new Color(-331277));
        limpiarCamposButton.setIcon(new ImageIcon(getClass().getResource("/images/24/clean.png")));
        limpiarCamposButton.setText("Limpiar Campos");
        contentPane.add(limpiarCamposButton, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, -1), null, new Dimension(250, -1), 0, false));
        regresarButton = new JButton();
        regresarButton.setBackground(new Color(-331277));
        regresarButton.setIcon(new ImageIcon(getClass().getResource("/images/24/back.png")));
        regresarButton.setText("Regresar");
        contentPane.add(regresarButton, new GridConstraints(7, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, -1), null, new Dimension(250, -1), 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        contentPane.add(scrollPane1, new GridConstraints(1, 2, 5, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(-1, 200), null, 0, false));
        tablaAlbumnes = new JTable();
        scrollPane1.setViewportView(tablaAlbumnes);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
