package com.softly.fonoteca.Vistas;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class CancionesVista extends JFrame implements CRUDView {
    public JPanel contentPane;
    public JTextField txtIDCancion;
    public JTextField txtTitulo;
    public JTextField txtDuracion;
    public JTextField txtBPM;
    public JTextField txtIdiomaCancion;
    public JTextField txtFechaLanzamiento;
    public JCheckBox esInstrumentalCheckBox;
    public JTextField txtBuscarCancion;
    public JButton btnAgregar;
    public JButton modificarButton;
    public JButton eliminarButton;
    public JButton limpiarButton;

    public JComboBox cmbAlbum;
    public JComboBox cmbGenero;
    public JComboBox cmbInterprete;
    public JButton regresarAlMenuButton;
    public JButton administarAlbumnesButton;
    public JButton administrarGenerosButton;
    public JButton administrarInterpretesButton;
    public JTable tablaCanciones;


    public CancionesVista() {
        super.setContentPane(contentPane);
    }

    @Override
    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    @Override
    public JButton getBtnModificar() {
        return modificarButton;
    }

    @Override
    public JButton getBtnEliminar() {
        return eliminarButton;
    }

    @Override
    public JButton getBtnRegresarMenu() {
        return regresarAlMenuButton;
    }

    @Override
    public JButton getBtnLimpiar() {
        return limpiarButton;
    }

    @Override
    public String getSearchText() {
        return txtBuscarCancion.getText();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(13, 3, new Insets(10, 30, 30, 30), 10, 10));
        contentPane.setBackground(new Color(-332568));
        final JLabel label1 = new JLabel();
        label1.setText("ID Cancion: ");
        contentPane.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtIDCancion = new JTextField();
        contentPane.add(txtIDCancion, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, 25), new Dimension(150, -1), new Dimension(250, -1), 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Titulo: ");
        contentPane.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtTitulo = new JTextField();
        contentPane.add(txtTitulo, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, 25), new Dimension(150, -1), new Dimension(250, -1), 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Duracion: ");
        contentPane.add(label3, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtDuracion = new JTextField();
        txtDuracion.setText("");
        contentPane.add(txtDuracion, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, 25), new Dimension(150, -1), new Dimension(250, -1), 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Tiempo BPM: ");
        contentPane.add(label4, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtBPM = new JTextField();
        contentPane.add(txtBPM, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, 25), new Dimension(150, -1), new Dimension(250, -1), 0, false));
        txtIdiomaCancion = new JTextField();
        contentPane.add(txtIdiomaCancion, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, 25), new Dimension(150, -1), new Dimension(250, -1), 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Idioma:");
        contentPane.add(label5, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("Fecha Lanzamiento: ");
        contentPane.add(label6, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtFechaLanzamiento = new JTextField();
        contentPane.add(txtFechaLanzamiento, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, 25), new Dimension(150, -1), new Dimension(250, -1), 0, false));
        final JLabel label7 = new JLabel();
        label7.setText("Album: ");
        contentPane.add(label7, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label8 = new JLabel();
        label8.setText("Genero: ");
        contentPane.add(label8, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label9 = new JLabel();
        label9.setText("Interprete Principal: ");
        contentPane.add(label9, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        esInstrumentalCheckBox = new JCheckBox();
        esInstrumentalCheckBox.setEnabled(false);
        esInstrumentalCheckBox.setText("Es Instrumental");
        contentPane.add(esInstrumentalCheckBox, new GridConstraints(10, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnAgregar = new JButton();
        btnAgregar.setBackground(new Color(-591112));
        btnAgregar.setText("Agregar");
        contentPane.add(btnAgregar, new GridConstraints(11, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(150, 25), null, new Dimension(150, -1), 0, false));
        modificarButton = new JButton();
        modificarButton.setBackground(new Color(-591112));
        modificarButton.setText("Modificar");
        contentPane.add(modificarButton, new GridConstraints(11, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(150, 25), null, new Dimension(150, -1), 0, false));
        eliminarButton = new JButton();
        eliminarButton.setBackground(new Color(-591112));
        eliminarButton.setText("Eliminar");
        contentPane.add(eliminarButton, new GridConstraints(11, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(150, 25), null, new Dimension(150, -1), 0, false));
        regresarAlMenuButton = new JButton();
        regresarAlMenuButton.setBackground(new Color(-591112));
        regresarAlMenuButton.setText("Regresar al menu");
        contentPane.add(regresarAlMenuButton, new GridConstraints(12, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(150, 25), null, new Dimension(150, -1), 0, false));
        limpiarButton = new JButton();
        limpiarButton.setBackground(new Color(-591112));
        limpiarButton.setText("Limpiar");
        contentPane.add(limpiarButton, new GridConstraints(12, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(150, 25), null, new Dimension(150, -1), 0, false));
        final JLabel label10 = new JLabel();
        Font label10Font = this.$$$getFont$$$(null, Font.BOLD, 24, label10.getFont());
        if (label10Font != null) label10.setFont(label10Font);
        label10.setIcon(new ImageIcon(getClass().getResource("/images/128/song.png")));
        label10.setText("Canciones");
        contentPane.add(label10, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cmbAlbum = new JComboBox();
        contentPane.add(cmbAlbum, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 25), null, null, 0, false));
        cmbGenero = new JComboBox();
        contentPane.add(cmbGenero, new GridConstraints(8, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 25), null, null, 0, false));
        cmbInterprete = new JComboBox();
        contentPane.add(cmbInterprete, new GridConstraints(9, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 25), null, null, 0, false));
        administarAlbumnesButton = new JButton();
        administarAlbumnesButton.setBackground(new Color(-591112));
        administarAlbumnesButton.setText("Administar Albumnes");
        contentPane.add(administarAlbumnesButton, new GridConstraints(7, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 25), null, null, 0, false));
        administrarGenerosButton = new JButton();
        administrarGenerosButton.setBackground(new Color(-591112));
        administrarGenerosButton.setText("Administrar Generos");
        contentPane.add(administrarGenerosButton, new GridConstraints(8, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 25), null, null, 0, false));
        administrarInterpretesButton = new JButton();
        administrarInterpretesButton.setBackground(new Color(-591112));
        administrarInterpretesButton.setText("Administrar Interpretes");
        contentPane.add(administrarInterpretesButton, new GridConstraints(9, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 25), null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        contentPane.add(scrollPane1, new GridConstraints(1, 2, 6, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(-1, 100), new Dimension(500, 400), 0, false));
        tablaCanciones = new JTable();
        tablaCanciones.setPreferredScrollableViewportSize(new Dimension(300, 350));
        scrollPane1.setViewportView(tablaCanciones);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
