package com.softly.fonoteca.Vistas;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

// 1. Extiende JFrame e implementa BaseView
public class MainView extends JFrame implements BaseView {

    // Estos componentes son creados y configurados por el diseñador de IntelliJ
    // y están asociados automáticamente al contentPane de este JFrame.
    public JPanel contentPane;
    public JButton usuariosButton;
    public JButton cancionesButton;
    public JButton reproduccionesButton;
    public JButton salirButton;
    public JButton calificacionesButton;

    public MainView() {
        // Usamos la implementación de JFrame (super) para configurar la ventana
        super.setContentPane(contentPane); // Usa el contentPane generado por el diseñador
        super.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        super.pack();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(5, 3, new Insets(50, 50, 50, 50), -1, -1));
        contentPane.setBackground(new Color(-331277));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$(null, -1, 36, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Sistema de Musica");
        contentPane.add(label1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        usuariosButton = new JButton();
        usuariosButton.setBackground(new Color(-33));
        usuariosButton.setBorderPainted(true);
        usuariosButton.setFocusPainted(false);
        Font usuariosButtonFont = this.$$$getFont$$$(null, -1, 22, usuariosButton.getFont());
        if (usuariosButtonFont != null) usuariosButton.setFont(usuariosButtonFont);
        usuariosButton.setIcon(new ImageIcon(getClass().getResource("/images/48/users.png")));
        usuariosButton.setText("Usuarios");
        contentPane.add(usuariosButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(300, -1), null, new Dimension(300, -1), 1, false));
        cancionesButton = new JButton();
        cancionesButton.setBackground(new Color(-33));
        cancionesButton.setFocusPainted(false);
        Font cancionesButtonFont = this.$$$getFont$$$(null, -1, 22, cancionesButton.getFont());
        if (cancionesButtonFont != null) cancionesButton.setFont(cancionesButtonFont);
        cancionesButton.setIcon(new ImageIcon(getClass().getResource("/images/48/song.png")));
        cancionesButton.setText("Canciones");
        contentPane.add(cancionesButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(300, -1), null, new Dimension(300, -1), 1, false));
        calificacionesButton = new JButton();
        calificacionesButton.setBackground(new Color(-33));
        calificacionesButton.setFocusPainted(false);
        Font calificacionesButtonFont = this.$$$getFont$$$(null, -1, 22, calificacionesButton.getFont());
        if (calificacionesButtonFont != null) calificacionesButton.setFont(calificacionesButtonFont);
        calificacionesButton.setIcon(new ImageIcon(getClass().getResource("/images/48/qualty.png")));
        calificacionesButton.setText("Calificaciones");
        contentPane.add(calificacionesButton, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(300, -1), null, new Dimension(300, -1), 1, false));
        reproduccionesButton = new JButton();
        reproduccionesButton.setBackground(new Color(-33));
        reproduccionesButton.setFocusPainted(false);
        Font reproduccionesButtonFont = this.$$$getFont$$$(null, -1, 22, reproduccionesButton.getFont());
        if (reproduccionesButtonFont != null) reproduccionesButton.setFont(reproduccionesButtonFont);
        reproduccionesButton.setIcon(new ImageIcon(getClass().getResource("/images/48/play.png")));
        reproduccionesButton.setText("Reproducciones");
        contentPane.add(reproduccionesButton, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(300, -1), null, new Dimension(300, -1), 1, false));
        final JLabel label2 = new JLabel();
        label2.setIcon(new ImageIcon(getClass().getResource("/images/128/music.png")));
        label2.setText("  ");
        contentPane.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        salirButton = new JButton();
        salirButton.setBackground(new Color(-33));
        salirButton.setFocusPainted(false);
        Font salirButtonFont = this.$$$getFont$$$(null, -1, 22, salirButton.getFont());
        if (salirButtonFont != null) salirButton.setFont(salirButtonFont);
        salirButton.setIcon(new ImageIcon(getClass().getResource("/images/48/exit.png")));
        salirButton.setText("Salir");
        contentPane.add(salirButton, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(300, -1), null, new Dimension(300, -1), 1, false));
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$(null, Font.PLAIN, 10, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setText("2025 © Softly Development");
        contentPane.add(label3, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_SOUTHEAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}