package com.softly.fonoteca.Vistas;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class UsuariosVista extends JFrame implements CRUDView {
    public JPanel contentPane;
    public JPasswordField passField;
    public JTextField txtApellido;
    public JTextField txtSexo;
    public JTextField txtPaisN;
    public JTextField txtPaisR;
    public JTextField txtNombre;
    public JTextField txtIdioma;
    public JTextField txtFechaN;
    public JTextField txtFechaR;
    public JTextField txtSearch;

    public JButton btnAgregar;
    public JButton btnModificar;
    public JButton btnEliminar;
    public JButton btnLimpiar;
    public JTextField txtEmail;
    public JButton regresarAlMenuButton;
    public JTable tablaUsuarios;


    public UsuariosVista() {
        super.setContentPane(contentPane);
    }

    @Override
    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    @Override
    public JButton getBtnModificar() {
        return btnModificar;
    }

    @Override
    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    @Override
    public JButton getBtnRegresarMenu() {
        return regresarAlMenuButton;
    }

    @Override
    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    @Override
    public String getSearchText() {
        return txtSearch.getText();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(14, 3, new Insets(10, 50, 50, 50), -1, -1));
        contentPane.setBackground(new Color(-329503));
        final JLabel label1 = new JLabel();
        label1.setText("Email: ");
        contentPane.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtEmail = new JTextField();
        contentPane.add(txtEmail, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, 25), new Dimension(150, -1), new Dimension(-1, 25), 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Contraseña: ");
        contentPane.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        passField = new JPasswordField();
        contentPane.add(passField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 25), new Dimension(150, -1), new Dimension(-1, 25), 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Nombres: ");
        contentPane.add(label3, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Apellidos");
        contentPane.add(label4, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtApellido = new JTextField();
        contentPane.add(txtApellido, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, 25), new Dimension(150, -1), new Dimension(-1, 25), 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Sexo: ");
        contentPane.add(label5, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtSexo = new JTextField();
        contentPane.add(txtSexo, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, 25), new Dimension(150, -1), new Dimension(-1, 25), 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("Fecha Nacimiento: ");
        contentPane.add(label6, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label7 = new JLabel();
        label7.setText("Pais de Nacimiento: ");
        contentPane.add(label7, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtPaisN = new JTextField();
        contentPane.add(txtPaisN, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, 25), new Dimension(150, -1), new Dimension(-1, 25), 0, false));
        final JLabel label8 = new JLabel();
        label8.setText("Pais de Residencia");
        contentPane.add(label8, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtPaisR = new JTextField();
        contentPane.add(txtPaisR, new GridConstraints(8, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, 25), new Dimension(150, -1), new Dimension(-1, 25), 0, false));
        txtNombre = new JTextField();
        contentPane.add(txtNombre, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, 25), new Dimension(150, -1), new Dimension(-1, 25), 0, false));
        final JLabel label9 = new JLabel();
        label9.setText("Idioma");
        contentPane.add(label9, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtIdioma = new JTextField();
        contentPane.add(txtIdioma, new GridConstraints(9, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, 25), new Dimension(150, -1), new Dimension(-1, 25), 0, false));
        final JLabel label10 = new JLabel();
        label10.setText("Fecha de Registro: ");
        contentPane.add(label10, new GridConstraints(10, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtFechaN = new JTextField();
        contentPane.add(txtFechaN, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, 25), new Dimension(150, -1), new Dimension(-1, 25), 0, false));
        txtFechaR = new JTextField();
        txtFechaR.setEditable(false);
        txtFechaR.setEnabled(false);
        contentPane.add(txtFechaR, new GridConstraints(10, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, 25), new Dimension(150, -1), new Dimension(-1, 25), 0, false));
        final JLabel label11 = new JLabel();
        Font label11Font = this.$$$getFont$$$(null, -1, 24, label11.getFont());
        if (label11Font != null) label11.setFont(label11Font);
        label11.setIcon(new ImageIcon(getClass().getResource("/images/128/users.png")));
        label11.setText("Usuarios");
        contentPane.add(label11, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnAgregar = new JButton();
        btnAgregar.setBackground(new Color(-331277));
        btnAgregar.setFocusPainted(false);
        btnAgregar.setForeground(new Color(-16777216));
        btnAgregar.setIcon(new ImageIcon(getClass().getResource("/images/24/save.png")));
        btnAgregar.setText("Agregar");
        contentPane.add(btnAgregar, new GridConstraints(12, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(200, 32), null, new Dimension(200, 32), 0, false));
        btnModificar = new JButton();
        btnModificar.setBackground(new Color(-331277));
        btnModificar.setFocusPainted(false);
        btnModificar.setForeground(new Color(-16777216));
        btnModificar.setIcon(new ImageIcon(getClass().getResource("/images/24/edit.png")));
        btnModificar.setText("Modificar");
        contentPane.add(btnModificar, new GridConstraints(12, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(200, 32), null, new Dimension(200, 32), 0, false));
        btnLimpiar = new JButton();
        btnLimpiar.setBackground(new Color(-331277));
        btnLimpiar.setFocusPainted(false);
        btnLimpiar.setForeground(new Color(-16777216));
        btnLimpiar.setIcon(new ImageIcon(getClass().getResource("/images/24/clean.png")));
        btnLimpiar.setText("Limpiar");
        contentPane.add(btnLimpiar, new GridConstraints(13, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(200, 32), null, new Dimension(200, 32), 0, false));
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(11, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(-1, 15), null, null, 0, false));
        btnEliminar = new JButton();
        btnEliminar.setBackground(new Color(-331277));
        btnEliminar.setFocusPainted(false);
        btnEliminar.setForeground(new Color(-16777216));
        btnEliminar.setIcon(new ImageIcon(getClass().getResource("/images/24/delete.png")));
        btnEliminar.setText("Eliminar");
        contentPane.add(btnEliminar, new GridConstraints(12, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(200, 32), null, new Dimension(200, 32), 0, false));
        regresarAlMenuButton = new JButton();
        regresarAlMenuButton.setBackground(new Color(-331277));
        regresarAlMenuButton.setFocusPainted(false);
        regresarAlMenuButton.setForeground(new Color(-16777216));
        regresarAlMenuButton.setIcon(new ImageIcon(getClass().getResource("/images/24/back.png")));
        regresarAlMenuButton.setText("Regresar al menu");
        contentPane.add(regresarAlMenuButton, new GridConstraints(13, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(200, 32), null, new Dimension(200, 32), 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setBackground(new Color(-1));
        contentPane.add(scrollPane1, new GridConstraints(1, 2, 10, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tablaUsuarios = new JTable();
        scrollPane1.setViewportView(tablaUsuarios);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
